import { RouterProvider, createRouter } from "@tanstack/react-router";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { routeTree } from "./routeTree.gen";
import "./styles/global.scss";

/**
 * SPA entry point. Builds the TanStack Router from the file-based route tree
 * (`routeTree.gen.ts`, regenerated by the router Vite plugin from `src/routes/`)
 * and mounts it. There is no SSR (ADR 0004) — this is the only render root.
 */
const router = createRouter({ routeTree });

// Make the router type available to every `useRouter`/`Link` call site, so route
// paths and params are checked. The interface-merging block is the documented
// TanStack Router pattern for a typed router singleton.
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById("root");
if (!rootElement) {
  throw new Error("Missing #root element in index.html");
}

createRoot(rootElement).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
);
