import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { routeTree } from "./routeTree.gen";
import "./styles/global.scss";

/**
 * SPA entry point. Builds the TanStack Router from the file-based route tree
 * (`routeTree.gen.ts`, regenerated by the router Vite plugin from `src/routes/`)
 * and mounts it inside a TanStack Query provider. There is no SSR (ADR 0004) —
 * this is the only render root.
 *
 * Server state (the review lists, the admin user list) lives in this one
 * `QueryClient`; pages read it with `useQuery` and mutate it with `useMutation`
 * + `invalidateQueries` instead of hand-rolled `useState`/`useEffect`/refetch.
 * The transport underneath stays `apiFetch` (see `api/client.ts`); the
 * better-auth session stays its own reactive store (see `auth/client.ts`) and is
 * deliberately NOT routed through Query.
 */
const router = createRouter({ routeTree });

// A single client for the whole app. `staleTime` lets a freshly-fetched list be
// reused across a quick remount/tab-switch without an immediate refetch;
// `retry: false` means an auth failure (401/403 ApiError) surfaces at once
// instead of being retried as if it were a transient network blip.
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 30_000,
      retry: false,
    },
  },
});

// Make the router type available to every `useRouter`/`Link` call site, so route
// paths and params are checked. The interface-merging block is the documented
// TanStack Router pattern for a typed router singleton.
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById("root");
if (!rootElement) {
  throw new Error("Missing #root element in index.html");
}

createRoot(rootElement).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
);
